### ISSUE TITLE
Weird error when

### ISSUE THREAD

**Issue by piegamesde** [michaellass/archlinux-java-run#6]
No matter what I call this command with, all I get is:

```
No suitable JVM found.
Available:         java-run java-home]
Default:           Unknown argument: get

USAGE:
  archlinux-java-run [-a|--min MIN] [-b|--max MAX] [-p|--package PKG]
                     [-f|--feature FEATURE] [-h|--help] [-v|--verbose]
                     [-d|--dry-run] [-j|--java-home]
                     -- JAVA_ARGS
Min. required:     6
Max. required:     20
Package required:  
Candidates:        
Features required: 
```

**Comment by michaellass** [comment]
Huh, I haven't seen that before. But maybe I introduced some regression in the latest release... Just to make sure:

* This is a new issue, correct? The previous version you tested in #2 did not show this issue?
* How did you call archlinux-java-run to get the above output? You wrote that it always happens, so just to exclude any issue with the command.
* What does `archlinux-java status` output for you?

**Comment by michaellass** [comment]
Could you please run the following command and post the output here?

`bash -v -x /usr/bin/archlinux-java-run -v -- -version 2>&1`

**Comment by michaellass** [comment]
Ah, now I know what is going on: You accidentally replaced /usr/bin/archlinux-java by the archlinux-java-run script when testing the version from #2. I can reproduce your error exactly doing this.

You should be able to fix this by running `pacman -S java-runtime-common`.

**Comment by piegamesde** [comment]
Thanks for the hints, I got it now. When trying out your patch, I accidentally wrote it to `/bin/archlinux-java` instead of `/bin/archlinux-java-run`. Reinstalling `java-runtime-common` fixed it for me.

**Comment by piegamesde** [comment]
You beat me to it :D

FWIW, `pacman -Qk` is worthless for checking against this kind of file corruption :(

**Comment by michaellass** [comment]
Yeah, by 20 seconds :smile:  Glad to hear that it's working now.

Yes, I think `pacman -Qk` only reports missing files. It seems like pacutils contains [a tool to verify checksums](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Listing_all_changed_files_from_packages).
