### ISSUE TITLE
"Unknown argument : --jar"

### ISSUE THREAD

**Issue by lululock71** [michaellass/archlinux-java-run#9]
Following the usage instructions, it is asked to use the "--jar" argument, which does not seems to exist (anymore ?).

`archlinux-java-run --max 8 --jar ./random_file.jar`
`Unknown argument: --jar`

The "--jar" argument does not appear in the help too.

**Comment by michaellass** [comment]
`-jar` (with one dash) is not an argument to `archlinux-java-run` but to `java` itself. The arguments for `java` need to be separated by `--`, i.e.,

```
archlinux-java-run --max 8 -- -jar ./random_file.jar
```
